/** MoeHu 随机图片 API 的壁纸分类配置（https://img.moehu.org/） */

export interface WallpaperCategory {
  /** pic.php?id= 参数 */
  id: string
  name: string
  nameEn: string
}

export interface WallpaperGroup {
  name: string
  nameEn: string
  items: WallpaperCategory[]
}

export const wallpaperGroups: WallpaperGroup[] = [
  {
    name: '二次元综合',
    nameEn: 'ACG General',
    items: [
      { id: 'img1', name: '图片一', nameEn: 'Random I' },
      { id: 'img2', name: '图片二', nameEn: 'Random II' },
      { id: 'sjpic', name: '竖屏壁纸', nameEn: 'Portrait' },
      { id: 'pc', name: '横屏壁纸', nameEn: 'Landscape' },
      { id: 'acghs', name: '黑丝', nameEn: 'Black Stockings' },
      { id: 'acgbs', name: '白丝', nameEn: 'White Stockings' },
      { id: 'kemonomimi', name: '兽耳', nameEn: 'Kemonomimi' },
      { id: 'yin', name: '白毛', nameEn: 'White Hair' },
      { id: 'xingk', name: '星空', nameEn: 'Starry Sky' },
      { id: 'loli', name: 'loli', nameEn: 'Loli' },
    ],
  },
  {
    name: '三次元综合',
    nameEn: 'Real World',
    items: [
      { id: 'xjj', name: '小姐姐', nameEn: 'Girls' },
      { id: 'gqbz', name: '高清风景壁纸', nameEn: 'HD Scenery' },
      { id: 'cat', name: '猫星人', nameEn: 'Cats' },
    ],
  },
  {
    name: '动漫系列',
    nameEn: 'Anime Series',
    items: [
      { id: 'saima', name: '赛马娘', nameEn: 'Uma Musume' },
      { id: 're0', name: 'RE0', nameEn: 'Re:Zero' },
      { id: 'sao', name: 'SAO', nameEn: 'SAO' },
      { id: 'yaowei', name: '妖精的尾巴', nameEn: 'Fairy Tail' },
      { id: 'gmzr', name: '鬼灭之刃', nameEn: 'Demon Slayer' },
      { id: '5huajia', name: '五等分的花嫁', nameEn: 'Quintessential Quintuplets' },
      { id: 'bingg', name: '冰菓', nameEn: 'Hyouka' },
      { id: 'kiminame', name: '你的名字', nameEn: 'Your Name' },
      { id: 'gongzhulj', name: '公主连接', nameEn: 'Princess Connect' },
      { id: 'spyfamily', name: '间谍过家家', nameEn: 'Spy x Family' },
      { id: 'camp', name: '摇曳露营', nameEn: 'Laid-Back Camp' },
      { id: 'yuruyuri', name: '摇曳百合', nameEn: 'YuruYuri' },
      { id: 'miyone', name: '天使降临到我身边', nameEn: 'Wataten!' },
      { id: 'xuebulai', name: '我们无法一起学习', nameEn: 'We Never Learn' },
      { id: 'nobiyori', name: '悠哉日常大王', nameEn: 'Non Non Biyori' },
      { id: 'kin-iro-mosaic', name: '黄金拼图', nameEn: 'Kiniro Mosaic' },
      { id: 'flag-ojousama', name: '转生恶役大小姐', nameEn: 'My Next Life as a Villainess' },
      { id: 'hori-to-miyamura', name: '崛与宫村', nameEn: 'Horimiya' },
      { id: 'saenai-heroine', name: '路人女主', nameEn: 'Saekano' },
      { id: 'mydcy', name: '喜欢本大爷竟然就你一个', nameEn: 'Oresuki' },
      { id: 'slime-300', name: '高原魔女', nameEn: 'Killing Slimes for 300 Years' },
      { id: 'fox-senko', name: '幼妻狐仙', nameEn: 'The Helpful Fox Senko-san' },
      { id: 'yu-gi-oh', name: '游戏王', nameEn: 'Yu-Gi-Oh!' },
      { id: 'lycoris-recoil', name: '莉可丽丝', nameEn: 'Lycoris Recoil' },
      { id: 'akame-ga-kill', name: '斩·赤红之瞳', nameEn: 'Akame ga Kill!' },
      { id: 'fgo', name: 'FGO', nameEn: 'FGO' },
      { id: 'k-on', name: '轻音', nameEn: 'K-ON!' },
      { id: 'lovelive', name: 'Lovelive', nameEn: 'Love Live!' },
      { id: 'overlord', name: 'Overlord', nameEn: 'Overlord' },
      { id: 'hentaiandneko', name: '变态王子与不笑猫', nameEn: 'HenNeko' },
      { id: 'majutsu-koushi', name: '不正经魔术师', nameEn: 'Akashic Records' },
      { id: 'kara-no-kyoukai', name: '空之境界', nameEn: 'The Garden of Sinners' },
      { id: 'kobayashi-no-dragon', name: '小林家的龙女仆', nameEn: 'Dragon Maid' },
      { id: 'toradora', name: '龙与虎', nameEn: 'Toradora!' },
      { id: 'tensei-slime', name: '转生史莱姆', nameEn: 'TenSura' },
      { id: 'hana-no-amae', name: '未闻花名', nameEn: 'Anohana' },
      { id: 'ika-usume', name: '乌贼娘', nameEn: 'Squid Girl' },
      { id: 'celia-claire', name: '小老师', nameEn: 'Celia Claire' },
      { id: 'kuma-bear', name: '熊熊勇闯异世界', nameEn: 'Kuma Kuma Kuma Bear' },
      { id: 'sekai-shukufuku', name: '为美好的世界献上祝福', nameEn: 'KonoSuba' },
    ],
  },
  {
    name: '游戏系列',
    nameEn: 'Game Series',
    items: [
      { id: 'ys', name: '原神', nameEn: 'Genshin Impact' },
      { id: 'mrfz', name: '明日方舟', nameEn: 'Arknights' },
      { id: 'blhx', name: '碧蓝航线', nameEn: 'Azur Lane' },
      { id: 'dongf', name: '车万', nameEn: 'Touhou' },
      { id: 'blda', name: '碧蓝档案', nameEn: 'Blue Archive' },
      { id: 'yzk', name: '缘之空', nameEn: 'Yosuga no Sora' },
      { id: 'snqx', name: '少女前线', nameEn: "Girls' Frontline" },
      { id: 'bh3', name: '崩坏三', nameEn: 'Honkai Impact 3rd' },
    ],
  },
  {
    name: '虚拟主播',
    nameEn: 'VTubers',
    items: [
      { id: 'gawr-gura', name: '小鲨鱼', nameEn: 'Gawr Gura' },
      { id: 'yukihana', name: '雪花菈米', nameEn: 'Yukihana Lamy' },
      { id: 'natsuiro', name: '夏色祭', nameEn: 'Natsuiro Matsuri' },
      { id: 'uruha-rushia', name: '润羽露西娅', nameEn: 'Uruha Rushia' },
      { id: 'hanazono-serena', name: '花园Serena', nameEn: 'Hanazono Serena' },
      { id: 'sasaki-saku', name: '笹木咲', nameEn: 'Sasaki Saku' },
      { id: 'tsunomaki-watame', name: '角卷绵芽', nameEn: 'Tsunomaki Watame' },
      { id: 'tokoyami-towa', name: '常暗永远', nameEn: 'Tokoyami Towa' },
      { id: 'amamiya-kokoro', name: '天宫心', nameEn: 'Amamiya Kokoro' },
      { id: 'usada-pekora', name: '兔田佩克菈', nameEn: 'Usada Pekora' },
      { id: 'ninomae', name: '一伊那尔栖', nameEn: "Ninomae Ina'nis" },
      { id: 'ookami-mio', name: '大神澪', nameEn: 'Ookami Mio' },
      { id: 'sara-hoshikawa', name: '星川莎拉', nameEn: 'Hoshikawa Sara' },
      { id: 'sakura-miko', name: '樱巫女', nameEn: 'Sakura Miko' },
      { id: 'holoen', name: 'HoloEN', nameEn: 'HoloEN' },
      { id: 'kizunaai', name: '绊爱', nameEn: 'Kizuna AI' },
      { id: 'kagura-nana', name: '神乐七奈', nameEn: 'Kagura Nana' },
      { id: 'kagura-mea', name: '神乐Mea', nameEn: 'Kagura Mea' },
      { id: 'fubuki', name: '白上吹雪', nameEn: 'Shirakami Fubuki' },
      { id: 'inugami-korone', name: '戌神沁音', nameEn: 'Inugami Korone' },
      { id: 'aqua', name: '阿夸', nameEn: 'Minato Aqua' },
      { id: 'nekomiya-hinata', name: '猫宫日向', nameEn: 'Nekomiya Hinata' },
    ],
  },
  {
    name: '表情包',
    nameEn: 'Stickers & Memes',
    items: [
      { id: 'Shiroko', name: '白子表情包', nameEn: 'Shiroko Stickers' },
      { id: 'bqb', name: '二次元表情包', nameEn: 'Anime Stickers' },
      { id: 'gcmm', name: '甘城猫猫', nameEn: 'Nacho Neko' },
      { id: 'mc', name: 'MC酱', nameEn: 'MC-chan' },
      { id: 'kemomimi', name: '兽耳酱', nameEn: 'Kemomimi-chan' },
      { id: 'miao', name: '三次元猫猫', nameEn: 'Real Cats' },
      { id: 'akqa', name: '阿夸', nameEn: 'Aqua' },
      { id: 'cheshire', name: '柴郡猫猫', nameEn: 'Cheshire' },
      { id: 'capoo', name: '猫猫虫咖波', nameEn: 'BugCat Capoo' },
      { id: 'ceciliabqb', name: '塞西莉亚(黑白)', nameEn: 'Cecilia (B&W)' },
      { id: 'cecilia', name: '塞西莉亚', nameEn: 'Cecilia' },
      { id: 'longtu', name: '龙图', nameEn: 'Dragon Memes' },
      { id: 'luox', name: '罗翔', nameEn: 'Luo Xiang' },
      { id: 'huaji', name: '滑稽', nameEn: 'Huaji' },
      { id: 'pand', name: '熊猫头', nameEn: 'Panda Head' },
      { id: 'tfkz', name: '同福客栈', nameEn: 'Tongfu Inn' },
      { id: 'ysbqb', name: '原神表情包', nameEn: 'Genshin Stickers' },
      { id: 'beifang', name: '北方酱', nameEn: 'Hoppou-chan' },
      { id: 'kenan', name: '柯南', nameEn: 'Detective Conan' },
      { id: 'tomandjerry', name: '猫和老鼠', nameEn: 'Tom and Jerry' },
      { id: 'whitevillain', name: '小白人', nameEn: 'White Villain' },
      { id: 'xiaohua', name: '小婳', nameEn: 'Xiaohua' },
      { id: 'toukui', name: '商业头盔', nameEn: 'Business Helmet' },
      { id: 'laofan', name: '牢饭降临到我身边', nameEn: 'Prison Memes' },
      { id: 'goum', name: '狗妈', nameEn: 'Dog Mom' },
      { id: 'sofei', name: '索菲', nameEn: 'Sofei' },
      { id: 'yingyy', name: '滑稽嘤嘤嘤', nameEn: 'Crying Huaji' },
      { id: 'caomeiguo', name: '草莓果酱', nameEn: 'Strawberry Jam' },
      { id: 'shawu', name: '和泉纱雾', nameEn: 'Izumi Sagiri' },
    ],
  },
  {
    name: '角色系列',
    nameEn: 'Characters',
    items: [
      { id: 'myn', name: '猫羽雫', nameEn: 'Nekoha Shizuku' },
      { id: 'ydmy', name: '樱岛麻衣', nameEn: 'Sakurajima Mai' },
      { id: 'miku', name: '初音未来', nameEn: 'Hatsune Miku' },
      { id: 'tianyi', name: '洛天依', nameEn: 'Luo Tianyi' },
      { id: 'gokou-ruri', name: '五更琉璃', nameEn: 'Gokou Ruri' },
      { id: 'mashiro', name: '椎名真白', nameEn: 'Shiina Mashiro' },
      { id: 'kano', name: '鹿乃', nameEn: 'Kano' },
      { id: 'saber', name: 'Saber', nameEn: 'Saber' },
      { id: 'yoshino', name: '四系乃', nameEn: 'Yoshino' },
      { id: 'misakimei', name: '见崎鸣', nameEn: 'Misaki Mei' },
      { id: 'akari', name: '阿卡林', nameEn: 'Akari' },
      { id: 'kanna', name: '康娜', nameEn: 'Kanna' },
      { id: 'miaops', name: '喵帕斯', nameEn: 'Renge (Nyanpasu)' },
      { id: 'nymph', name: '妮姆芙', nameEn: 'Nymph' },
      { id: 'noel', name: '诺艾尔', nameEn: 'Noel' },
      { id: 'kurumi', name: '时崎狂三', nameEn: 'Tokisaki Kurumi' },
      { id: 'violet', name: '薇尔莉特', nameEn: 'Violet Evergarden' },
      { id: 'shinobu', name: '忍野忍', nameEn: 'Oshino Shinobu' },
      { id: 'kazuki', name: '风见一姬', nameEn: 'Kazami Kazuki' },
      { id: 'iliya', name: '伊莉雅', nameEn: 'Illya' },
      { id: 'beatrice', name: '碧翠丝', nameEn: 'Beatrice' },
      { id: 'umr', name: '土间埋', nameEn: 'Doma Umaru' },
      { id: 'rem', name: '雷姆', nameEn: 'Rem' },
      { id: 'aharen', name: '阿波连', nameEn: 'Aharen' },
      { id: '02', name: '国家队02', nameEn: 'Zero Two' },
      { id: 'aniya', name: '阿尼亚', nameEn: 'Anya' },
      { id: 'takagi', name: '高木', nameEn: 'Takagi' },
      { id: 'misaka-mikoto', name: '御坂美琴', nameEn: 'Misaka Mikoto' },
      { id: 'yor', name: '约尔', nameEn: 'Yor' },
      { id: 'mizuhara', name: '水原千鹤', nameEn: 'Mizuhara Chizuru' },
      { id: 'nico', name: '矢泽妮可', nameEn: 'Yazawa Nico' },
      { id: 'tangkk', name: '唐可可', nameEn: 'Tang Keke' },
      { id: 'eru', name: '千反田爱瑠', nameEn: 'Chitanda Eru' },
      { id: 'asuna', name: '亚丝娜', nameEn: 'Asuna' },
      { id: 'chiro', name: '香风智乃', nameEn: 'Kafuu Chino' },
      { id: 'karyl', name: '凯露', nameEn: 'Karyl' },
      { id: 'haibara', name: '灰原哀', nameEn: 'Haibara Ai' },
      { id: 'hinatsuru', name: '雏鹤爱', nameEn: 'Hinatsuru Ai' },
      { id: 'shimarin', name: '志摩凛', nameEn: 'Shima Rin' },
      { id: 'rikka', name: '小鸟游六花', nameEn: 'Takanashi Rikka' },
      { id: 'katoumegumi', name: '加藤惠', nameEn: 'Kato Megumi' },
      { id: 'yukino', name: '雪之下雪乃', nameEn: 'Yukinoshita Yukino' },
      { id: 'siesta', name: '谢丝塔', nameEn: 'Siesta' },
      { id: 'hayasakaai', name: '早坂爱', nameEn: 'Hayasaka Ai' },
      { id: 'kaguya', name: '四宫辉夜', nameEn: 'Shinomiya Kaguya' },
      { id: 'haruhi', name: '凉宫春日', nameEn: 'Suzumiya Haruhi' },
      { id: 'chika', name: '藤原千花', nameEn: 'Fujiwara Chika' },
      { id: 'nezuko', name: '祢豆子', nameEn: 'Nezuko' },
      { id: 'onoderaoosaki', name: '小野寺小咲', nameEn: 'Onodera Kosaki' },
      { id: 'nakanomiku', name: '中野三玖', nameEn: 'Nakano Miku' },
      { id: 'elaina', name: '伊蕾娜', nameEn: 'Elaina' },
      { id: 'ruiko', name: '佐天泪子', nameEn: 'Saten Ruiko' },
      { id: 'kuroko', name: '白井黑子', nameEn: 'Shirai Kuroko' },
      { id: 'konata', name: '泉此方', nameEn: 'Izumi Konata' },
      { id: 'shiroganekei', name: '白银圭', nameEn: 'Shirogane Kei' },
      { id: 'linomiko', name: '伊井野弥子', nameEn: 'Iino Miko' },
      { id: 'kanade', name: '立华奏', nameEn: 'Tachibana Kanade' },
      { id: 'kitagawa-marin', name: '喜多川海梦', nameEn: 'Kitagawa Marin' },
      { id: 'amayadori-machi', name: '雨宿町', nameEn: 'Amayadori Machi' },
      { id: 'makise-kurisu', name: '牧濑红莉栖', nameEn: 'Makise Kurisu' },
      { id: 'lsla', name: '艾拉', nameEn: 'Isla' },
      { id: 'yuzuriha-inori', name: '蝶祈', nameEn: 'Yuzuriha Inori' },
      { id: 'uranus-queen', name: '伊卡洛斯', nameEn: 'Ikaros' },
      { id: 'yashiro-nene', name: '八寻宁宁', nameEn: 'Yashiro Nene' },
      { id: 'filo', name: '菲洛', nameEn: 'Filo' },
      { id: 'shokuho-isaki', name: '食蜂操祈', nameEn: 'Shokuhou Misaki' },
      { id: 'gasai-yuno', name: '我妻由乃', nameEn: 'Gasai Yuno' },
      { id: 'nagatoro-hayase', name: '长瀞同学', nameEn: 'Nagatoro' },
      { id: 'noname-kumo', name: '蜘蛛子', nameEn: 'Kumoko' },
      { id: 'izumi-sagiri', name: '和泉纱雾', nameEn: 'Izumi Sagiri' },
      { id: 'kuriyama-mirai', name: '栗山未来', nameEn: 'Kuriyama Mirai' },
      { id: 'nyaruko', name: '奈亚子', nameEn: 'Nyaruko' },
      { id: 'ogiwara-sayu', name: '沙优', nameEn: 'Ogiwara Sayu' },
      { id: 'blois', name: '维包子', nameEn: 'Blois' },
      { id: 'miniwa-tsumiki', name: '摘希', nameEn: 'Miniwa Tsumiki' },
    ],
  },
]
