/** MoeHu 随机图片 API 的壁纸分类配置（https://img.moehu.org/） */

export interface WallpaperCategory {
  /** pic.php?id= 参数 */
  id: string
  name: string
}

export interface WallpaperGroup {
  name: string
  items: WallpaperCategory[]
}

export const wallpaperGroups: WallpaperGroup[] = [
  {
    name: '二次元综合',
    items: [
      { id: 'img1', name: '图片一' },
      { id: 'img2', name: '图片二' },
      { id: 'sjpic', name: '竖屏壁纸' },
      { id: 'pc', name: '横屏壁纸' },
      { id: 'acghs', name: '黑丝' },
      { id: 'acgbs', name: '白丝' },
      { id: 'kemonomimi', name: '兽耳' },
      { id: 'yin', name: '白毛' },
      { id: 'xingk', name: '星空' },
      { id: 'loli', name: 'loli' },
    ],
  },
  {
    name: '三次元综合',
    items: [
      { id: 'xjj', name: '小姐姐' },
      { id: 'gqbz', name: '高清风景壁纸' },
      { id: 'cat', name: '猫星人' },
    ],
  },
  {
    name: '动漫系列',
    items: [
      { id: 'saima', name: '赛马娘' },
      { id: 're0', name: 'RE0' },
      { id: 'sao', name: 'SAO' },
      { id: 'yaowei', name: '妖精的尾巴' },
      { id: 'gmzr', name: '鬼灭之刃' },
      { id: '5huajia', name: '五等分的花嫁' },
      { id: 'bingg', name: '冰菓' },
      { id: 'kiminame', name: '你的名字' },
      { id: 'gongzhulj', name: '公主连接' },
      { id: 'spyfamily', name: '间谍过家家' },
      { id: 'camp', name: '摇曳露营' },
      { id: 'yuruyuri', name: '摇曳百合' },
      { id: 'miyone', name: '天使降临到我身边' },
      { id: 'xuebulai', name: '我们无法一起学习' },
      { id: 'nobiyori', name: '悠哉日常大王' },
      { id: 'kin-iro-mosaic', name: '黄金拼图' },
      { id: 'flag-ojousama', name: '转生恶役大小姐' },
      { id: 'hori-to-miyamura', name: '崛与宫村' },
      { id: 'saenai-heroine', name: '路人女主' },
      { id: 'mydcy', name: '喜欢本大爷竟然就你一个' },
      { id: 'slime-300', name: '高原魔女' },
      { id: 'fox-senko', name: '幼妻狐仙' },
      { id: 'yu-gi-oh', name: '游戏王' },
      { id: 'lycoris-recoil', name: '莉可丽丝' },
      { id: 'akame-ga-kill', name: '斩·赤红之瞳' },
      { id: 'fgo', name: 'FGO' },
      { id: 'k-on', name: '轻音' },
      { id: 'lovelive', name: 'Lovelive' },
      { id: 'overlord', name: 'Overlord' },
      { id: 'hentaiandneko', name: '变态王子与不笑猫' },
      { id: 'majutsu-koushi', name: '不正经魔术师' },
      { id: 'kara-no-kyoukai', name: '空之境界' },
      { id: 'kobayashi-no-dragon', name: '小林家的龙女仆' },
      { id: 'toradora', name: '龙与虎' },
      { id: 'tensei-slime', name: '转生史莱姆' },
      { id: 'hana-no-amae', name: '未闻花名' },
      { id: 'ika-usume', name: '乌贼娘' },
      { id: 'celia-claire', name: '小老师' },
      { id: 'kuma-bear', name: '熊熊勇闯异世界' },
      { id: 'sekai-shukufuku', name: '为美好的世界献上祝福' },
    ],
  },
  {
    name: '游戏系列',
    items: [
      { id: 'ys', name: '原神' },
      { id: 'mrfz', name: '明日方舟' },
      { id: 'blhx', name: '碧蓝航线' },
      { id: 'dongf', name: '车万' },
      { id: 'blda', name: '碧蓝档案' },
      { id: 'yzk', name: '缘之空' },
      { id: 'snqx', name: '少女前线' },
      { id: 'bh3', name: '崩坏三' },
    ],
  },
  {
    name: '虚拟主播',
    items: [
      { id: 'gawr-gura', name: '小鲨鱼' },
      { id: 'yukihana', name: '雪花菈米' },
      { id: 'natsuiro', name: '夏色祭' },
      { id: 'uruha-rushia', name: '润羽露西娅' },
      { id: 'hanazono-serena', name: '花园Serena' },
      { id: 'sasaki-saku', name: '笹木咲' },
      { id: 'tsunomaki-watame', name: '角卷绵芽' },
      { id: 'tokoyami-towa', name: '常暗永远' },
      { id: 'amamiya-kokoro', name: '天宫心' },
      { id: 'usada-pekora', name: '兔田佩克菈' },
      { id: 'ninomae', name: '一伊那尔栖' },
      { id: 'ookami-mio', name: '大神澪' },
      { id: 'sara-hoshikawa', name: '星川莎拉' },
      { id: 'sakura-miko', name: '樱巫女' },
      { id: 'holoen', name: 'HoloEN' },
      { id: 'kizunaai', name: '绊爱' },
      { id: 'kagura-nana', name: '神乐七奈' },
      { id: 'kagura-mea', name: '神乐Mea' },
      { id: 'fubuki', name: '白上吹雪' },
      { id: 'inugami-korone', name: '戌神沁音' },
      { id: 'aqua', name: '阿夸' },
      { id: 'nekomiya-hinata', name: '猫宫日向' },
    ],
  },
  {
    name: '表情包',
    items: [
      { id: 'Shiroko', name: '白子表情包' },
      { id: 'bqb', name: '二次元表情包' },
      { id: 'gcmm', name: '甘城猫猫' },
      { id: 'mc', name: 'MC酱' },
      { id: 'kemomimi', name: '兽耳酱' },
      { id: 'miao', name: '三次元猫猫' },
      { id: 'akqa', name: '阿夸' },
      { id: 'cheshire', name: '柴郡猫猫' },
      { id: 'capoo', name: '猫猫虫咖波' },
      { id: 'ceciliabqb', name: '塞西莉亚(黑白)' },
      { id: 'cecilia', name: '塞西莉亚' },
      { id: 'longtu', name: '龙图' },
      { id: 'luox', name: '罗翔' },
      { id: 'huaji', name: '滑稽' },
      { id: 'pand', name: '熊猫头' },
      { id: 'tfkz', name: '同福客栈' },
      { id: 'ysbqb', name: '原神表情包' },
      { id: 'beifang', name: '北方酱' },
      { id: 'kenan', name: '柯南' },
      { id: 'tomandjerry', name: '猫和老鼠' },
      { id: 'whitevillain', name: '小白人' },
      { id: 'xiaohua', name: '小婳' },
      { id: 'toukui', name: '商业头盔' },
      { id: 'laofan', name: '牢饭降临到我身边' },
      { id: 'goum', name: '狗妈' },
      { id: 'sofei', name: '索菲' },
      { id: 'yingyy', name: '滑稽嘤嘤嘤' },
      { id: 'caomeiguo', name: '草莓果酱' },
      { id: 'shawu', name: '和泉纱雾' },
    ],
  },
  {
    name: '角色系列',
    items: [
      { id: 'myn', name: '猫羽雫' },
      { id: 'ydmy', name: '樱岛麻衣' },
      { id: 'miku', name: '初音未来' },
      { id: 'tianyi', name: '洛天依' },
      { id: 'gokou-ruri', name: '五更琉璃' },
      { id: 'mashiro', name: '椎名真白' },
      { id: 'kano', name: '鹿乃' },
      { id: 'saber', name: 'Saber' },
      { id: 'yoshino', name: '四系乃' },
      { id: 'misakimei', name: '见崎鸣' },
      { id: 'akari', name: '阿卡林' },
      { id: 'kanna', name: '康娜' },
      { id: 'miaops', name: '喵帕斯' },
      { id: 'nymph', name: '妮姆芙' },
      { id: 'noel', name: '诺艾尔' },
      { id: 'kurumi', name: '时崎狂三' },
      { id: 'violet', name: '薇尔莉特' },
      { id: 'shinobu', name: '忍野忍' },
      { id: 'kazuki', name: '风见一姬' },
      { id: 'iliya', name: '伊莉雅' },
      { id: 'beatrice', name: '碧翠丝' },
      { id: 'umr', name: '土间埋' },
      { id: 'rem', name: '雷姆' },
      { id: 'aharen', name: '阿波连' },
      { id: '02', name: '国家队02' },
      { id: 'aniya', name: '阿尼亚' },
      { id: 'takagi', name: '高木' },
      { id: 'misaka-mikoto', name: '御坂美琴' },
      { id: 'yor', name: '约尔' },
      { id: 'mizuhara', name: '水原千鹤' },
      { id: 'nico', name: '矢泽妮可' },
      { id: 'tangkk', name: '唐可可' },
      { id: 'eru', name: '千反田爱瑠' },
      { id: 'asuna', name: '亚丝娜' },
      { id: 'chiro', name: '香风智乃' },
      { id: 'karyl', name: '凯露' },
      { id: 'haibara', name: '灰原哀' },
      { id: 'hinatsuru', name: '雏鹤爱' },
      { id: 'shimarin', name: '志摩凛' },
      { id: 'rikka', name: '小鸟游六花' },
      { id: 'katoumegumi', name: '加藤惠' },
      { id: 'yukino', name: '雪之下雪乃' },
      { id: 'siesta', name: '谢丝塔' },
      { id: 'hayasakaai', name: '早坂爱' },
      { id: 'kaguya', name: '四宫辉夜' },
      { id: 'haruhi', name: '凉宫春日' },
      { id: 'chika', name: '藤原千花' },
      { id: 'nezuko', name: '祢豆子' },
      { id: 'onoderaoosaki', name: '小野寺小咲' },
      { id: 'nakanomiku', name: '中野三玖' },
      { id: 'elaina', name: '伊蕾娜' },
      { id: 'ruiko', name: '佐天泪子' },
      { id: 'kuroko', name: '白井黑子' },
      { id: 'konata', name: '泉此方' },
      { id: 'shiroganekei', name: '白银圭' },
      { id: 'linomiko', name: '伊井野弥子' },
      { id: 'kanade', name: '立华奏' },
      { id: 'kitagawa-marin', name: '喜多川海梦' },
      { id: 'amayadori-machi', name: '雨宿町' },
      { id: 'makise-kurisu', name: '牧濑红莉栖' },
      { id: 'lsla', name: '艾拉' },
      { id: 'yuzuriha-inori', name: '蝶祈' },
      { id: 'uranus-queen', name: '伊卡洛斯' },
      { id: 'yashiro-nene', name: '八寻宁宁' },
      { id: 'filo', name: '菲洛' },
      { id: 'shokuho-isaki', name: '食蜂操祈' },
      { id: 'gasai-yuno', name: '我妻由乃' },
      { id: 'nagatoro-hayase', name: '长瀞同学' },
      { id: 'noname-kumo', name: '蜘蛛子' },
      { id: 'izumi-sagiri', name: '和泉纱雾' },
      { id: 'kuriyama-mirai', name: '栗山未来' },
      { id: 'nyaruko', name: '奈亚子' },
      { id: 'ogiwara-sayu', name: '沙优' },
      { id: 'blois', name: '维包子' },
      { id: 'miniwa-tsumiki', name: '摘希' },
    ],
  },
]
